### ISSUE TITLE
 unsupported token:0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 不支持WETH的Protocol是什么原因

### ISSUE THREAD

**Issue by LuckAction** [Loopring/loopr-ios#110]
返回结果
▿ 3 elements
  ▿ 0 : 2 elements
    - key : "id"
    - value : B705B1B2-AB57-4BB6-8106-2ABF5D9B39F3
  ▿ 1 : 2 elements
    - key : "error"
    ▿ value : 2 elements
      ▿ 0 : 2 elements
        - key : "code"
        - value : -32000
      ▿ 1 : 2 elements
        - key : "message"
        - value : unsupported token:0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
  ▿ 2 : 2 elements
    - key : "jsonrpc"
    - value : 2.0

发送参数
 rawDictionary : 3 elements
    ▿ 0 : 2 elements
      - key : "id"
      - value : "B705B1B2-AB57-4BB6-8106-2ABF5D9B39F3"
    ▿ 1 : 2 elements
      - key : "method"
      - value : "loopring_submitOrder"
    ▿ 2 : 2 elements
      - key : "params"
      ▿ value : 1 element
        ▿ 0 : 18 elements
          ▿ 0 : 2 elements
            - key : "lrcFee"
            - value : "0x13e699cdcfb16b"
          ▿ 1 : 2 elements
            - key : "authPrivateKey"
            - value : "0ab4427e1fb1e025df99d732acf54e4368ce3f42b3a1c0d382af3f8680361896"
          ▿ 2 : 2 elements
            - key : "amountB"
            - value : "0xde0b6b3a7640000"
          ▿ 3 : 2 elements
            - key : "authAddr"
            - value : "0xA4BabA2B8caE907a096A83277C90c8e9900aff6e"
          ▿ 4 : 2 elements
            - key : "v"
            - value : 28
          ▿ 5 : 2 elements
            - key : "walletAddress"
            - value : "0xb94065482ad64d4c2b9252358d746b39e820a582"
          ▿ 6 : 2 elements
            - key : "tokenS"
            - value : "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
          ▿ 7 : 2 elements
            - key : "protocol"
            - value : "0x8d8812b72d1e4ffCeC158D25f56748b7d67c1e78"
          ▿ 8 : 2 elements
            - key : "amountS"
            - value : "0x92291029f6a00"
          ▿ 9 : 2 elements
            - key : "validUntil"
            - value : "0x5b02bfce"
          ▿ 10 : 2 elements
            - key : "buyNoMoreThanAmountB"
            - value : true
          ▿ 11 : 2 elements
            - key : "r"
            - value : "972c63bf8c4f585aafd2d38b3d37f3d4b1c6987e430b9f487557299dedebcba2"
          ▿ 12 : 2 elements
            - key : "owner"
            - value : "0xafb87869FD4132e8700e8678765ceCd6B259cdA8"
          ▿ 13 : 2 elements
            - key : "tokenB"
            - value : "0xdd974d5c2e2928dea5f71b9825b8b646686bd200"
          ▿ 14 : 2 elements
            - key : "s"
            - value : "04b579f34d9267038964299380c6841bb6a5ed16d5b76d0c0541b2714ebb95c4"
          ▿ 15 : 2 elements
            - key : "delegateAddress"
            - value : "0x17233e07c67d086464fD408148c3ABB56245FA64"
          ▿ 16 : 2 elements
            - key : "validSince"
            - value : "0x5b02b1be"
          ▿ 17 : 2 elements
            - key : "marginSplitPercentage"
            - value : 50

**Comment by xiaowheat** [comment]
@LuckAction 能不能描述一些是哪段代码？具体是什么问题？上面的内容，比较难理解。

**Comment by LuckAction** [comment]
交易下单操作，下面那段是参数，上面是返回结果，结果报unsupported token:0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
这个是WETH的protocol

**Comment by xiaowheat** [comment]
```
    func getWethAddress() {
        var address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        if let weth = TokenDataManager.shared.getTokenBySymbol("WETH") {
            address = weth.protocol_value
        }
        var error: NSError? = nil
        self.wethAddress = GethNewAddressFromHex(address, &error)
    }
```
请看这段代码
