### ISSUE TITLE
could not insert new outlet connection

### ISSUE THREAD

**Issue by sunnycn2013** [Loopring/loopr-ios#118]
整个工程无法拖拽 IBOutlet  属性

<img width="395" alt="2018-07-07 15 19 17" src="https://user-images.githubusercontent.com/3810388/42408024-3ac0f950-81f9-11e8-990a-df17c4974d90.png">

**Comment by sunnycn2013** [comment]
@xiaowheat   编译速度比前几周慢了很多呀，swift混编也不至于这么慢呀

**Comment by xiaowheat** [comment]
整个工程无法拖拽 IBOutlet 属性，是Xcode的bug。请清空，重新编译。

**Comment by xiaowheat** [comment]
编译速度 请修改Optimization level。

**Comment by sunnycn2013** [comment]
清楚了DeviceData也不行，用当前Xcode随便打卡一个其他的共层就是好的，loopr是不是改了啥环境配置

**Comment by sunnycn2013** [comment]
@xiaowheat  你用的Xcode是最新的beta版本的还是 老的正式版9.3？

**Comment by xiaowheat** [comment]
具体看一下Xcode的build settings。我们现在还是使用正式版的。

**Comment by sunnycn2013** [comment]
我换了两台电脑，都是又问题，我换别的工程就是好的，
![2d52afa4-656d-44ba-a91d-b63fae2e8301](https://user-images.githubusercontent.com/3810388/42417951-16532424-82c8-11e8-8a85-13fb66f944f2.png)

拖拽链接IBOutlet时报上面的错，我用的也是8.3的版本，你电脑上不报错？

**Comment by xiaowheat** [comment]
没有。iOS开发，不一定要用 IBOutlet
