### ISSUE TITLE
最新的系统keystore无法登录，少了keystore 类型判断

### ISSUE THREAD

**Issue by sunnycn2013** [Loopring/loopr-ios#119]
ScanQRCodeViewController.swift

else if QRCodeMethod.isKeystore(content: qrContent) {
            return QRCodeType.keystore
        } else {
            return QRCodeType.undefined
        }

**Comment by xiaowheat** [comment]
@sunnycn2013 这和Swift编译的优化级别有关。如果把编译的优化级别提高，就不会有问题。

**Comment by sunnycn2013** [comment]
👌

**Comment by xiaowheat** [comment]
最新代码已经修复。谢谢
