### ISSUE TITLE
bug提交：App闪退的情况

### ISSUE THREAD

**Issue by YorkChen-Loopring** [Loopring/loopr-ios#122]
停留在交易所一段时间或下单过程中、或是添加自选代币过程中、或是资产未加载出的时候、都会出现闪退的情况，例如：钱包的资产页面未加载出来的时候，进入去中心化交易所会闪退，资产加载很慢的时候进入交易所模块：首先是拉取不到数据、其次就是即使数据显示出，点击数据也会很大几率闪退。

**Comment by xiaowheat** [comment]
在9月2日发布的版本0.9.8已经修复。我们调整了向Relay发送请求的顺序。谢谢。
