### ISSUE TITLE
Bug提交：交易所下单

### ISSUE THREAD

**Issue by YorkChen-Loopring** [Loopring/loopr-ios#128]
1.下单之后，单价被强制转换成1比1的兑换。
    2.移动4G网络下单过程很慢，那个确定的按钮变灰色了，之后需要等待不到1分钟才提示下单成功。

**Comment by xiaowheat** [comment]
已经修复1. 下单之后，单价被强制转换成1比1的兑换。

2. 安装一个新的版本，也会解决。
