### ISSUE TITLE
优化建议：代码注释

### ISSUE THREAD

**Issue by ccqwert** [Loopring/loopr-ios#136]
希望能及时完善代码注释hope to perfect code annotation in time

**Comment by xiaowheat** [comment]
@ccqwert 请问是指哪一部分的代码注释？

**Comment by ccqwert** [comment]
主要是接口文档LoopringAPIRequest

**Comment by xiaowheat** [comment]
@ccqwert  接口文档LoopringAPIRequest, 请参考https://loopring.github.io/relay-cluster/relay_api_spec_v2.html

**Comment by xiaowheat** [comment]
如果是其他问题，请写新的issue。
