### ISSUE TITLE
导出KEYSTORE和私钥存在缺陷

### ISSUE THREAD

**Issue by q120471762** [Loopring/loopr-ios#139]
1、管理钱包页面导出KEYSTORE输入任意密码都能成功导出
2、导出私钥不用输入密码就能看到私钥

**Comment by xiaowheat** [comment]
@q120471762 1、管理钱包页面导出KEYSTORE输入任意密码都能成功导出，如果是用私钥导入的地址，现在是用任意密码都能成功导出的。请到https://loopr.loopring.io 验证，用私钥导入的地址，如何导出keystore。

**Comment by xiaowheat** [comment]
2、导出私钥不用输入密码就能看到私钥： 因为现在app是不用app本身的密码。所以的密码都是和解析地址有关。

**Comment by xiaowheat** [comment]
若有其他的问题，请重新提交issue，或提供更多信息。
