### ISSUE TITLE
Scan a QR code of private key to import a wallet

### ISSUE THREAD

**Issue by xiaowheat** [Loopring/loopr-ios#30]
<img width="309" alt="screen shot 2018-03-04 at 5 56 29 pm" src="https://user-images.githubusercontent.com/18495858/36954224-6b6a794a-1fd5-11e8-906a-eb2fda120157.png">

The right navigation item is to scan a QR code to import a wallet. We can type a private key. Scanning a QR code will make it easy to import.

**Comment by yimenglovesai** [comment]
I can take this one over.

**Comment by xiaowheat** [comment]
@yimenglovesai Good job.
