### ISSUE TITLE
compile error under Xcode9.3 cuz SwiftyJSON isn't compatible with Swift 4.1

### ISSUE THREAD

**Issue by lhalcyon** [Loopring/loopr-ios#46]
![image](https://user-images.githubusercontent.com/21357951/38738136-e98fa090-3f63-11e8-9ccf-19d1bdd86973.png)

**Comment by xiaowheat** [comment]
@kongliangzhong The default version of Swift in Xcode 9.3 is 4.1. SwiftyJSON isn't compatible with Swift 4.1. You have to change the version of Swift to 4.0. You can set the in the Build Settings. Please the screenshot

<img width="1277" alt="screen shot 2018-04-13 at 8 49 15 am" src="https://user-images.githubusercontent.com/18495858/38744845-bf6d274a-3ef7-11e8-987d-3f3b0da619dd.png">

**Comment by lhalcyon** [comment]
I know the problem lies between SwiftyJSON and Swift4.1 ,  but  the Swift compile option only support 3.2 and 4.1 .   So here is the solution I take , quite hack , work for now :( 
I copy the SwiftJSON file to my project and remove the dependency in pod file. 

hope SwiftJSON fix this problem soon .  btw thx for replying!

**Comment by xiaowheat** [comment]
To avoid the similar errors happen again in the future, we moved SwiftJSON file to the project and removed the dependency in pod file. The current version of Swift in the project is still 4.0. However, it's easier to manage SwiftJSON across different versions of Swift.

Thank you for reporting the issue. Close it.
