### ISSUE TITLE
error occurs when huge balance return in OnBalanceResponse

### ISSUE THREAD

**Issue by lhalcyon** [Loopring/loopr-ios#47]
![image](https://user-images.githubusercontent.com/21357951/38766220-8e318c24-4001-11e8-986e-21c45f228165.png)
error occurs at line 122 in CurrentAppWalletDataManager

**Comment by lhalcyon** [comment]
Not exactly .  it's the token.decimal .

**Comment by xiaowheat** [comment]
@lhalcyon Thank you for reporting the issue. Do you have an error message or a screenshot with the error? We also notice that the performance drops when loading huge data.

**Comment by lhalcyon** [comment]
it's not found after I pull the  latest code . ty 
em  , I hear from the wechat that the iOS app will be in test in April  . Is that certain ?

**Comment by xiaowheat** [comment]
That's the plan. We will send out the app through TestFlight. We are working on it.
