### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yimenglovesai** [Loopring/loopr-ios#49]
Geth can't be built. 
Xcode version: Version 9.3 (9E145)
Toolchain: Swift 4.0 RELEASE

<img width="711" alt="screen shot 2018-04-14 at 2 08 35 pm" src="https://user-images.githubusercontent.com/38386601/38772515-6a7ed8ea-3fed-11e8-8a40-5403093aa932.png">

**Comment by yimenglovesai** [comment]
https://github.com/krzyzanowskim/CryptoSwift/issues/601

**Comment by xiaowheat** [comment]
@yimenglovesai Do you still have the issue?
