### ISSUE TITLE
Setup continuous integration for PR and commits.

### ISSUE THREAD

**Issue by xiaowheat** [Loopring/loopr-ios#53]
We have implemented unit tests for the app. We should have a continue integration to run those unit tests for PR and commits. We could use https://travis-ci.org

**Comment by yimenglovesai** [comment]
i can take this over.

**Comment by xiaowheat** [comment]
@yimenglovesai We want to hold it until June.

**Comment by xiaowheat** [comment]
Refer: https://www.hackingwithswift.com/articles/100/how-to-validate-code-changes-using-circleci?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B352

**Comment by xiaowheat** [comment]
Completed. Please see https://travis-ci.com/Loopring/loopr-ios
