### ISSUE TITLE
wallet name will get concatenated is too long 

### ISSUE THREAD

**Issue by yimenglovesai** [Loopring/loopr-ios#56]
<img width="276" alt="screen shot 2018-04-15 at 5 11 14 pm" src="https://user-images.githubusercontent.com/38386601/38785090-479aa6d6-40d0-11e8-94a0-0edcdce46999.png">

it should be limited either in settings, or users should be allowed to have a longer name fully displayed.

**Comment by xiaowheat** [comment]
@yimenglovesai Could you help us fix this issue? The width is limited to a fix value 176 in SettingManageWalletTableViewCell.xib file. It should be screen width.

**Comment by xiaowheat** [comment]
Great. Thank you.
