### ISSUE TITLE
round button design rules

### ISSUE THREAD

**Issue by yimenglovesai** [Loopring/loopr-ios#61]
<img width="338" alt="screen shot 2018-04-17 at 12 14 33 am" src="https://user-images.githubusercontent.com/38386601/38854124-57fb12ea-41d4-11e8-9b67-c6f03d600d0a.png">

current corner radius on buttons look good on most of buttons, but just shooting an idea. if the button is short, it might look weird somehow. according to Naoto Fukasawa's industrial design idea, round rect items looks perfect with 2.5R on the corner, which means corner radius looks perfect at 2.5mm. 

here are some examples: https://www.stylepark.com/en/news/an-essential-truth-in-the-chaos-of-multiplicity

**Comment by xiaowheat** [comment]
I update the UI style of the button in this commit 2cc96e4b9b50076ef92b51a4b7b99c6c2dc5aab2

The default height is 47. The left and right paddings are 15.
