### ISSUE TITLE
is web3jswift like web3j java?

### ISSUE THREAD

**Issue by lhalcyon** [Loopring/loopr-ios#62]
an Android app is in the plan for my team . We 're going to find some lib that  is equal to the loopr-ios-sdk in the iOS demo . May I get some directions from ur team?

**Comment by xiaowheat** [comment]
@lhalcyon Great to hear that you are working on Android app. We haven't started Android development yet. We can discuss more when we start.

One fundamental framework in iOS app is Geth, Official Go implementation of the Ethereum protocol. They also support Android You can download https://ethereum.github.io/go-ethereum/downloads/  Beside importing source code from web3jsSwift, we have also implemented some functions. We didn't find a single third party lib to fit all we need.
